var APPS = [
  {
    id: 'unpickle',
    name: 'UnPickle',
    verb: 'unwrapping',
    tagline: 'Get out of it.',
    blurb: 'A decision app for the moments you have talked yourself into a corner. One question at a time until the knot comes loose.',
    platform: 'iPhone · iPad',
    price: 'Free',
    version: '3.2',
    features: ['One question per screen', 'Nothing leaves the device', 'Shortcuts and widgets'],
  },
  {
    id: 'mealplanner',
    name: 'Meal Planner',
    verb: 'ticking off',
    tagline: 'Seven dinners, one list.',
    blurb: 'Plan the week, get the shopping list, tick it off in the aisle. No accounts, no recipe feed, no video of someone making it.',
    platform: 'iPhone · iPad · Mac',
    price: '£4.99',
    version: '2.1',
    features: ['Week view, drag to move', 'List merges duplicates', 'Share to anyone'],
  },
  {
    id: 'unjumble',
    name: 'UnJumble',
    verb: 'recording',
    tagline: 'Say it, then sort it.',
    blurb: 'Talk at it while the thought is still moving. UnJumble transcribes on device and hands you back something with a shape.',
    platform: 'iPhone',
    price: '£2.99',
    version: '1.4',
    features: ['On-device transcription', 'Live rearranging', 'Export to Notes or Markdown'],
  },
  {
    id: 'riverly',
    name: 'Riverly',
    verb: 'navigating',
    tagline: 'Read the water.',
    blurb: 'Inland navigation for small craft. Depth, locks, moorings and the bits the big charts leave out.',
    platform: 'iPhone · iPad · Watch',
    price: '£9.99',
    version: '4.0',
    features: ['Offline charts', 'Lock and mooring data', 'Watch complication'],
  },
];
